version: "3"
services:
  react-app:
    image: rajiv075/articles_client:latest
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: rajiv075/articles_server:latest
    stdin_open: true
    ports:
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
