version: "3"
services:
  react-app:
    image: urumuladora/spe-project-final_client:latest
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - Articles-app
  api-server:
    image: urumuladora/spe-project-final_server:latest
    ports:
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
